### ISSUE TITLE
Empty module -- requesting some love

### ISSUE THREAD

**Issue by jackdpeterson** [geocoder-php/GeocoderModule#1]
It looks like the ZF2 implementation is empty. Is there any planned activity for this library?

**Comment by willdurand** [comment]
ping @Gounlaf

**Comment by Gounlaf** [comment]
Work still in progress [here](https://github.com/smartandgeek/GeocoderModule). It's working, but unit tests are required.

**Comment by jguittard** [comment]
Just submitted a PR. Unit tests, CS checks, everything :)
Let me know your thoughts

**Comment by jackdpeterson** [comment]
Sweet, I'll check it out this week.

**Comment by jguittard** [comment]
Fixed in #2

**Comment by jackdpeterson** [comment]
Delayed love is still love! Thanks :-)
